import type { ExerciseDef, MovementPattern } from './types';

/**
 * Exercise catalogue. Every exercise the program can ever log — primaries from
 * the block tables, the document's "X or Y" alternatives, the Part 7 core
 * drills, and every substitute named in the Part 3 table — so that a
 * substitute logs against its own history.
 *
 * `substitutes` is the Part 3 list for the exercise's pattern, in the
 * document's order, minus the exercise itself. Where Part 3 says "the other
 * curl machine" the list is written per exercise.
 */

// Part 3 substitution table, by pattern, in order of preference.
const SUBS: Record<MovementPattern, readonly string[]> = {
  'horizontal-press': ['machine-chest-press', 'smith-bench', 'weighted-push-up'],
  'incline-press': ['machine-incline-press', 'smith-incline', 'low-to-high-cable-press'],
  'vertical-press': ['machine-shoulder-press', 'smith-ohp', 'high-incline-db-press'],
  'chest-isolation': ['db-fly-incline', 'deficit-push-up'],
  'side-delt': ['machine-lateral-raise', 'lean-away-db-lateral', 'wide-grip-upright-row'],
  'vertical-pull': [
    'assisted-pull-up-machine',
    'kneeling-single-arm-cable-pulldown',
    'straight-arm-pulldown',
  ],
  'horizontal-row': ['machine-row', 'single-arm-db-row', 'inverted-row'],
  'rear-delt': ['cable-rear-delt-fly', 'bent-over-db-rear-fly', 'face-pull'],
  biceps: ['cable-curl', 'machine-curl', 'db-curl'],
  triceps: ['cable-triceps-alt-attachment', 'db-overhead-extension', 'close-grip-push-up'],
  squat: ['leg-press', 'smith-squat', 'bulgarian-split-squat-db', 'goblet-squat'],
  'hip-hinge': ['db-rdl', 'back-extension-45-loaded', 'cable-pull-through'],
  // "The other curl machine" is written per exercise below.
  'knee-flexion': ['nordic-curl-negatives', 'slider-leg-curl'],
  'knee-extension': ['sissy-squat', 'narrow-stance-leg-press'],
  'hip-thrust': ['machine-hip-thrust', 'single-leg-db-hip-thrust', 'cable-pull-through'],
  calves: ['calf-press-leg-press', 'single-leg-db-calf-raise'],
  forearms: ['wrist-roller', 'plate-pinch-hold', 'dead-hang'],
  'loaded-ab-flexion': ['machine-crunch', 'weighted-decline-crunch'],
  'core-bracing': [],
};

function subs(pattern: MovementPattern, self: string, extraFirst: string[] = []): string[] {
  return [...extraFirst, ...SUBS[pattern]].filter((id) => id !== self);
}

type Catalogue = Record<string, ExerciseDef>;

export const EXERCISES = {
  // ───────────── PUSH primaries ─────────────
  'barbell-bench-press': {
    name: 'Barbell bench press',
    pattern: 'horizontal-press',
    equipment: 'barbell-upper',
    role: 'main',
    substitutes: subs('horizontal-press', 'barbell-bench-press'),
  },
  'incline-db-press': {
    name: 'Incline DB press (~30°)',
    pattern: 'incline-press',
    equipment: 'dumbbell',
    role: 'secondary',
    substitutes: subs('incline-press', 'incline-db-press'),
  },
  'seated-db-ohp': {
    name: 'Seated DB overhead press',
    pattern: 'vertical-press',
    equipment: 'dumbbell',
    role: 'secondary',
    substitutes: subs('vertical-press', 'seated-db-ohp'),
  },
  'cable-fly': {
    name: 'Cable fly (mid-height)',
    pattern: 'chest-isolation',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('chest-isolation', 'cable-fly'),
  },
  'cable-lateral-raise': {
    name: 'Cable lateral raise',
    pattern: 'side-delt',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('side-delt', 'cable-lateral-raise'),
  },
  'overhead-cable-triceps-extension': {
    name: 'Overhead cable triceps extension',
    pattern: 'triceps',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('triceps', 'overhead-cable-triceps-extension'),
  },
  'cable-pressdown': {
    name: 'Cable pressdown',
    pattern: 'triceps',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('triceps', 'cable-pressdown'),
  },
  'machine-shoulder-press': {
    name: 'Machine shoulder press',
    pattern: 'vertical-press',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('vertical-press', 'machine-shoulder-press'),
  },
  'flat-db-press': {
    name: 'Flat DB press',
    pattern: 'horizontal-press',
    equipment: 'dumbbell',
    role: 'secondary',
    substitutes: subs('horizontal-press', 'flat-db-press'),
  },
  'pec-deck': {
    name: 'Pec-deck',
    pattern: 'chest-isolation',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('chest-isolation', 'pec-deck'),
  },
  'db-lateral-raise': {
    name: 'DB lateral raise',
    pattern: 'side-delt',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('side-delt', 'db-lateral-raise'),
  },
  'skullcrusher-ez': {
    name: 'Skullcrusher (EZ bar)',
    pattern: 'triceps',
    equipment: 'barbell-upper',
    role: 'isolation',
    substitutes: subs('triceps', 'skullcrusher-ez'),
  },
  'rope-pressdown': {
    name: 'Rope pressdown',
    pattern: 'triceps',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('triceps', 'rope-pressdown'),
  },
  'standing-barbell-ohp': {
    name: 'Standing barbell OHP',
    pattern: 'vertical-press',
    equipment: 'barbell-upper',
    role: 'main',
    substitutes: subs('vertical-press', 'standing-barbell-ohp'),
  },
  'incline-barbell-bench': {
    name: 'Incline barbell bench (30°)',
    pattern: 'incline-press',
    equipment: 'barbell-upper',
    role: 'main',
    substitutes: subs('incline-press', 'incline-barbell-bench'),
  },
  'machine-chest-press': {
    name: 'Machine chest press',
    pattern: 'horizontal-press',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('horizontal-press', 'machine-chest-press'),
  },
  'seated-barbell-ohp': {
    name: 'Seated barbell OHP',
    pattern: 'vertical-press',
    equipment: 'barbell-upper',
    role: 'main',
    substitutes: subs('vertical-press', 'seated-barbell-ohp'),
  },

  // ───────────── PULL primaries ─────────────
  'lat-pulldown': {
    name: 'Lat pulldown',
    pattern: 'vertical-pull',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('vertical-pull', 'lat-pulldown'),
  },
  'chest-supported-row': {
    name: 'Chest-supported row',
    pattern: 'horizontal-row',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    notes: 'Machine, or DB on an incline bench.',
    substitutes: subs('horizontal-row', 'chest-supported-row'),
  },
  'seated-cable-row': {
    name: 'Seated cable row (neutral grip)',
    pattern: 'horizontal-row',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('horizontal-row', 'seated-cable-row'),
  },
  'reverse-pec-deck': {
    name: 'Reverse pec-deck',
    pattern: 'rear-delt',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('rear-delt', 'reverse-pec-deck'),
  },
  'ez-bar-curl': {
    name: 'EZ-bar curl',
    pattern: 'biceps',
    equipment: 'barbell-upper',
    role: 'isolation',
    substitutes: subs('biceps', 'ez-bar-curl'),
  },
  'hammer-curl': {
    name: 'Hammer curl',
    pattern: 'biceps',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('biceps', 'hammer-curl'),
  },
  'db-wrist-curl': {
    name: 'DB wrist curl',
    pattern: 'forearms',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('forearms', 'db-wrist-curl'),
  },
  'pull-up': {
    name: 'Pull-up',
    pattern: 'vertical-pull',
    equipment: 'bodyweight',
    role: 'main',
    defaultIncrementLb: 5,
    notes:
      'Load is added weight. 0 = strict bodyweight. Enter assistance as a negative load (e.g. −30).',
    substitutes: subs('vertical-pull', 'pull-up'),
  },
  'barbell-row': {
    name: 'Barbell row',
    pattern: 'horizontal-row',
    equipment: 'barbell-upper',
    role: 'main',
    substitutes: subs('horizontal-row', 'barbell-row'),
  },
  'single-arm-cable-row': {
    name: 'Single-arm cable row',
    pattern: 'horizontal-row',
    equipment: 'machine-cable',
    role: 'secondary',
    perSide: true,
    substitutes: subs('horizontal-row', 'single-arm-cable-row'),
  },
  'cable-rear-delt-fly': {
    name: 'Cable rear-delt fly',
    pattern: 'rear-delt',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('rear-delt', 'cable-rear-delt-fly'),
  },
  'incline-db-curl': {
    name: 'Incline DB curl',
    pattern: 'biceps',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('biceps', 'incline-db-curl'),
  },
  'reverse-ez-curl': {
    name: 'Reverse EZ curl',
    pattern: 'biceps',
    equipment: 'barbell-upper',
    role: 'isolation',
    substitutes: subs('biceps', 'reverse-ez-curl'),
  },
  'behind-back-wrist-curl': {
    name: 'Behind-back wrist curl',
    pattern: 'forearms',
    equipment: 'barbell-upper',
    role: 'isolation',
    substitutes: subs('forearms', 'behind-back-wrist-curl'),
  },
  'neutral-grip-pulldown': {
    name: 'Neutral-grip pulldown',
    pattern: 'vertical-pull',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('vertical-pull', 'neutral-grip-pulldown'),
  },
  't-bar-row': {
    name: 'T-bar row',
    pattern: 'horizontal-row',
    equipment: 'barbell-upper',
    role: 'secondary',
    substitutes: subs('horizontal-row', 't-bar-row'),
  },
  'meadows-row': {
    name: 'Meadows row',
    pattern: 'horizontal-row',
    equipment: 'barbell-upper',
    role: 'secondary',
    perSide: true,
    substitutes: subs('horizontal-row', 'meadows-row'),
  },

  // ───────────── LEGS primaries ─────────────
  'high-bar-back-squat': {
    name: 'High-bar back squat',
    pattern: 'squat',
    equipment: 'barbell-lower',
    role: 'main',
    substitutes: subs('squat', 'high-bar-back-squat'),
  },
  'romanian-deadlift': {
    name: 'Romanian deadlift',
    pattern: 'hip-hinge',
    equipment: 'barbell-lower',
    role: 'main',
    substitutes: subs('hip-hinge', 'romanian-deadlift'),
  },
  'leg-press': {
    name: 'Leg press',
    pattern: 'squat',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    defaultIncrementLb: 10, // Part 1.4 groups leg press with the lower-body barbell lifts.
    substitutes: subs('squat', 'leg-press'),
  },
  'leg-extension': {
    name: 'Leg extension',
    pattern: 'knee-extension',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('knee-extension', 'leg-extension'),
  },
  'seated-leg-curl': {
    name: 'Seated leg curl',
    pattern: 'knee-flexion',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    notes: 'Seated > lying for hamstring growth (reasonably supported).',
    substitutes: subs('knee-flexion', 'seated-leg-curl', ['lying-leg-curl']),
  },
  'standing-calf-raise': {
    name: 'Standing calf raise',
    pattern: 'calves',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    notes: 'Full stretch at bottom, 2s pause.',
    substitutes: subs('calves', 'standing-calf-raise'),
  },
  'seated-calf-raise': {
    name: 'Seated calf raise',
    pattern: 'calves',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('calves', 'seated-calf-raise'),
  },
  'bulgarian-split-squat-db': {
    name: 'Bulgarian split squat (DB)',
    pattern: 'squat',
    equipment: 'dumbbell',
    role: 'secondary',
    perSide: true,
    substitutes: subs('squat', 'bulgarian-split-squat-db'),
  },
  'barbell-hip-thrust': {
    name: 'Barbell hip thrust',
    pattern: 'hip-thrust',
    equipment: 'barbell-lower',
    role: 'secondary',
    substitutes: subs('hip-thrust', 'barbell-hip-thrust'),
  },
  'lying-leg-curl': {
    name: 'Lying leg curl',
    pattern: 'knee-flexion',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('knee-flexion', 'lying-leg-curl', ['seated-leg-curl']),
  },
  'conventional-deadlift': {
    name: 'Conventional deadlift',
    pattern: 'hip-hinge',
    equipment: 'barbell-lower',
    role: 'main',
    notes: 'Never grind deadlifts.',
    substitutes: subs('hip-hinge', 'conventional-deadlift'),
  },
  'hack-squat': {
    name: 'Hack squat',
    pattern: 'squat',
    equipment: 'machine-cable',
    role: 'main',
    machineGuided: true,
    defaultIncrementLb: 10, // Part 1.4 groups hack squat with the lower-body barbell lifts.
    substitutes: subs('squat', 'hack-squat'),
  },

  // ───────────── Core / APT drills (Part 7) ─────────────
  'dead-bug': {
    name: 'Dead bug',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    perSide: true,
    loadable: false,
    notes: 'Lower back pressed flat — this is the exercise.',
    substitutes: [],
  },
  'rkc-plank': {
    name: 'RKC plank',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    repUnit: 'seconds',
    loadable: false,
    notes: 'Max tension, glutes squeezed, posterior tilt.',
    substitutes: [],
  },
  'cable-crunch': {
    name: 'Cable crunch',
    pattern: 'loaded-ab-flexion',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('loaded-ab-flexion', 'cable-crunch'),
  },
  'hanging-knee-raise': {
    name: 'Hanging knee raise',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    loadable: false,
    notes: "Curl the pelvis, don't swing.",
    substitutes: [],
  },
  'side-plank': {
    name: 'Side plank',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    repUnit: 'seconds',
    perSide: true,
    loadable: false,
    substitutes: [],
  },
  'hanging-leg-raise-progression': {
    name: 'Hanging knee raise → straight-leg raise progression',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    loadable: false,
    substitutes: [],
  },
  'ab-wheel-knees': {
    name: 'Ab wheel from knees',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    loadable: false,
    substitutes: [],
  },
  'suitcase-carry': {
    name: 'Suitcase carry',
    pattern: 'core-bracing',
    equipment: 'dumbbell',
    role: 'core',
    repUnit: 'metres',
    perSide: true,
    substitutes: [],
  },
  'hanging-leg-raise': {
    name: 'Hanging leg raise',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    loadable: false,
    substitutes: [],
  },
  'ab-wheel-extended': {
    name: 'Ab wheel, extend range toward standing',
    pattern: 'core-bracing',
    equipment: 'bodyweight',
    role: 'core',
    loadable: false,
    substitutes: [],
  },

  // ───────────── Substitutes (Part 3) ─────────────
  'smith-bench': {
    name: 'Smith bench',
    pattern: 'horizontal-press',
    equipment: 'barbell-upper',
    role: 'main',
    machineGuided: true,
    substitutes: subs('horizontal-press', 'smith-bench'),
  },
  'weighted-push-up': {
    name: 'Weighted push-up (feet elevated)',
    pattern: 'horizontal-press',
    equipment: 'bodyweight',
    role: 'secondary',
    defaultIncrementLb: 5,
    substitutes: subs('horizontal-press', 'weighted-push-up'),
  },
  'machine-incline-press': {
    name: 'Machine incline press',
    pattern: 'incline-press',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('incline-press', 'machine-incline-press'),
  },
  'smith-incline': {
    name: 'Smith incline',
    pattern: 'incline-press',
    equipment: 'barbell-upper',
    role: 'main',
    machineGuided: true,
    substitutes: subs('incline-press', 'smith-incline'),
  },
  'low-to-high-cable-press': {
    name: 'Low-to-high cable press',
    pattern: 'incline-press',
    equipment: 'machine-cable',
    role: 'secondary',
    substitutes: subs('incline-press', 'low-to-high-cable-press'),
  },
  'smith-ohp': {
    name: 'Smith OHP',
    pattern: 'vertical-press',
    equipment: 'barbell-upper',
    role: 'main',
    machineGuided: true,
    substitutes: subs('vertical-press', 'smith-ohp'),
  },
  'high-incline-db-press': {
    name: 'High-incline DB press (60°+)',
    pattern: 'vertical-press',
    equipment: 'dumbbell',
    role: 'secondary',
    substitutes: subs('vertical-press', 'high-incline-db-press'),
  },
  'db-fly-incline': {
    name: 'DB fly (slight incline)',
    pattern: 'chest-isolation',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('chest-isolation', 'db-fly-incline'),
  },
  'deficit-push-up': {
    name: 'Deficit push-up (slow, deep)',
    pattern: 'chest-isolation',
    equipment: 'bodyweight',
    role: 'isolation',
    substitutes: subs('chest-isolation', 'deficit-push-up'),
  },
  'machine-lateral-raise': {
    name: 'Machine lateral raise',
    pattern: 'side-delt',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('side-delt', 'machine-lateral-raise'),
  },
  'lean-away-db-lateral': {
    name: 'Lean-away DB lateral',
    pattern: 'side-delt',
    equipment: 'dumbbell',
    role: 'isolation',
    perSide: true,
    substitutes: subs('side-delt', 'lean-away-db-lateral'),
  },
  'wide-grip-upright-row': {
    name: 'Wide-grip upright row (to nipple height)',
    pattern: 'side-delt',
    equipment: 'barbell-upper',
    role: 'isolation',
    substitutes: subs('side-delt', 'wide-grip-upright-row'),
  },
  'assisted-pull-up-machine': {
    name: 'Assisted pull-up machine',
    pattern: 'vertical-pull',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    notes: 'Log the assistance as a negative load so less assistance reads as progress.',
    substitutes: subs('vertical-pull', 'assisted-pull-up-machine'),
  },
  'kneeling-single-arm-cable-pulldown': {
    name: 'Kneeling single-arm cable pulldown',
    pattern: 'vertical-pull',
    equipment: 'machine-cable',
    role: 'secondary',
    perSide: true,
    substitutes: subs('vertical-pull', 'kneeling-single-arm-cable-pulldown'),
  },
  'straight-arm-pulldown': {
    name: 'Straight-arm pulldown',
    pattern: 'vertical-pull',
    equipment: 'machine-cable',
    role: 'isolation',
    notes: 'Lats only.',
    substitutes: subs('vertical-pull', 'straight-arm-pulldown'),
  },
  'machine-row': {
    name: 'Machine row',
    pattern: 'horizontal-row',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('horizontal-row', 'machine-row'),
  },
  'single-arm-db-row': {
    name: 'Single-arm DB row',
    pattern: 'horizontal-row',
    equipment: 'dumbbell',
    role: 'secondary',
    perSide: true,
    substitutes: subs('horizontal-row', 'single-arm-db-row'),
  },
  'inverted-row': {
    name: 'Inverted row',
    pattern: 'horizontal-row',
    equipment: 'bodyweight',
    role: 'secondary',
    substitutes: subs('horizontal-row', 'inverted-row'),
  },
  'bent-over-db-rear-fly': {
    name: 'Bent-over DB rear fly',
    pattern: 'rear-delt',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('rear-delt', 'bent-over-db-rear-fly'),
  },
  'face-pull': {
    name: 'Face pull',
    pattern: 'rear-delt',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('rear-delt', 'face-pull'),
  },
  'cable-curl': {
    name: 'Cable curl',
    pattern: 'biceps',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('biceps', 'cable-curl'),
  },
  'machine-curl': {
    name: 'Machine curl',
    pattern: 'biceps',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('biceps', 'machine-curl'),
  },
  'db-curl': {
    name: 'DB curl (any variant)',
    pattern: 'biceps',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('biceps', 'db-curl'),
  },
  'cable-triceps-alt-attachment': {
    name: 'Cable triceps (alternate attachment)',
    pattern: 'triceps',
    equipment: 'machine-cable',
    role: 'isolation',
    substitutes: subs('triceps', 'cable-triceps-alt-attachment'),
  },
  'db-overhead-extension': {
    name: 'DB overhead extension',
    pattern: 'triceps',
    equipment: 'dumbbell',
    role: 'isolation',
    substitutes: subs('triceps', 'db-overhead-extension'),
  },
  'close-grip-push-up': {
    name: 'Close-grip push-up',
    pattern: 'triceps',
    equipment: 'bodyweight',
    role: 'isolation',
    substitutes: subs('triceps', 'close-grip-push-up'),
  },
  'smith-squat': {
    name: 'Smith squat',
    pattern: 'squat',
    equipment: 'barbell-lower',
    role: 'main',
    machineGuided: true,
    substitutes: subs('squat', 'smith-squat'),
  },
  'goblet-squat': {
    name: 'Goblet squat',
    pattern: 'squat',
    equipment: 'dumbbell',
    role: 'secondary',
    notes: 'Last resort — loading runs out fast.',
    substitutes: subs('squat', 'goblet-squat'),
  },
  'db-rdl': {
    name: 'DB RDL',
    pattern: 'hip-hinge',
    equipment: 'dumbbell',
    role: 'main',
    substitutes: subs('hip-hinge', 'db-rdl'),
  },
  'back-extension-45-loaded': {
    name: '45° back extension (loaded)',
    pattern: 'hip-hinge',
    equipment: 'bodyweight',
    role: 'secondary',
    machineGuided: true,
    defaultIncrementLb: 5,
    substitutes: subs('hip-hinge', 'back-extension-45-loaded'),
  },
  'cable-pull-through': {
    name: 'Cable pull-through',
    pattern: 'hip-hinge',
    equipment: 'machine-cable',
    role: 'secondary',
    substitutes: subs('hip-hinge', 'cable-pull-through'),
  },
  'nordic-curl-negatives': {
    name: 'Nordic curl negatives',
    pattern: 'knee-flexion',
    equipment: 'bodyweight',
    role: 'isolation',
    loadable: false,
    substitutes: subs('knee-flexion', 'nordic-curl-negatives', ['seated-leg-curl', 'lying-leg-curl']),
  },
  'slider-leg-curl': {
    name: 'Slider / stability-ball leg curl',
    pattern: 'knee-flexion',
    equipment: 'bodyweight',
    role: 'isolation',
    loadable: false,
    substitutes: subs('knee-flexion', 'slider-leg-curl', ['seated-leg-curl', 'lying-leg-curl']),
  },
  'sissy-squat': {
    name: 'Sissy squat',
    pattern: 'knee-extension',
    equipment: 'bodyweight',
    role: 'isolation',
    substitutes: subs('knee-extension', 'sissy-squat'),
  },
  'narrow-stance-leg-press': {
    name: 'Narrow-stance leg press',
    pattern: 'knee-extension',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    defaultIncrementLb: 10,
    notes: 'Partial substitute.',
    substitutes: subs('knee-extension', 'narrow-stance-leg-press'),
  },
  'machine-hip-thrust': {
    name: 'Machine hip thrust',
    pattern: 'hip-thrust',
    equipment: 'machine-cable',
    role: 'secondary',
    machineGuided: true,
    substitutes: subs('hip-thrust', 'machine-hip-thrust'),
  },
  'single-leg-db-hip-thrust': {
    name: 'Single-leg DB hip thrust',
    pattern: 'hip-thrust',
    equipment: 'dumbbell',
    role: 'secondary',
    perSide: true,
    substitutes: subs('hip-thrust', 'single-leg-db-hip-thrust'),
  },
  'calf-press-leg-press': {
    name: 'Calf press on leg press',
    pattern: 'calves',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    defaultIncrementLb: 10,
    substitutes: subs('calves', 'calf-press-leg-press'),
  },
  'single-leg-db-calf-raise': {
    name: 'Single-leg DB calf raise off a step',
    pattern: 'calves',
    equipment: 'dumbbell',
    role: 'isolation',
    perSide: true,
    substitutes: subs('calves', 'single-leg-db-calf-raise'),
  },
  'wrist-roller': {
    name: 'Wrist roller',
    pattern: 'forearms',
    equipment: 'bodyweight',
    role: 'isolation',
    substitutes: subs('forearms', 'wrist-roller'),
  },
  'plate-pinch-hold': {
    name: 'Plate pinch hold',
    pattern: 'forearms',
    equipment: 'bodyweight',
    role: 'isolation',
    repUnit: 'seconds',
    substitutes: subs('forearms', 'plate-pinch-hold'),
  },
  'dead-hang': {
    name: 'Dead hang',
    pattern: 'forearms',
    equipment: 'bodyweight',
    role: 'isolation',
    repUnit: 'seconds',
    substitutes: subs('forearms', 'dead-hang'),
  },
  'machine-crunch': {
    name: 'Machine crunch',
    pattern: 'loaded-ab-flexion',
    equipment: 'machine-cable',
    role: 'isolation',
    machineGuided: true,
    substitutes: subs('loaded-ab-flexion', 'machine-crunch'),
  },
  'weighted-decline-crunch': {
    name: 'Weighted decline crunch',
    pattern: 'loaded-ab-flexion',
    equipment: 'bodyweight',
    role: 'isolation',
    substitutes: subs('loaded-ab-flexion', 'weighted-decline-crunch'),
  },
} as const satisfies Catalogue;

export type ExerciseId = keyof typeof EXERCISES;

export function getExercise(id: string): ExerciseDef {
  const def = (EXERCISES as Catalogue)[id];
  if (!def) throw new Error(`Unknown exercise id: ${id}`);
  return def;
}

export function isExerciseId(id: string): id is ExerciseId {
  return Object.prototype.hasOwnProperty.call(EXERCISES, id);
}

/**
 * Part 1.5: the calibration nudge is only ever offered on machine/cable
 * isolation work — never on squat, bench, deadlift, OHP or any barbell lift.
 */
export function isCalibrationEligible(id: string): boolean {
  const def = getExercise(id);
  return def.equipment === 'machine-cable' && def.role === 'isolation';
}
